# Generated by Django 3.2.9 on 2021-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('availableCash', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredTime', models.DateTimeField(auto_now_add=True)),
                ('executedTime', models.DateTimeField(null=True)),
                ('success', models.BooleanField(null=True)),
                ('cashAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destinationAccount', models.ManyToManyField(related_name='debits', to='transactions.Account')),
                ('sourceAccount', models.ManyToManyField(related_name='withdrawals', to='transactions.Account')),
            ],
        ),
    ]
