# Generated by Django 3.2.9 on 2021-11-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destinationAccount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinationAccount',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='debits', to='transactions.account'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sourceAccount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sourceAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='withdrawals', to='transactions.account'),
            preserve_default=False,
        ),
    ]
